# templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: johnpaul-app
spec:
  selector:
    matchLabels:
      app: johnpaul-app
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: johnpaul-app
    spec:
      containers:
        - name: johnpaul-app
          image: johnpaul/test:1.12.0
          ports:
            - containerPort: 2368
          env:
            - name: url
              {{- if .Values.prodUrlSchema }}
              value: http://{{ .Values.baseUrl }}
              {{- else }}
              value: http://{{ .Values.datacenter }}.non-prod.{{ .Values.baseUrl }}
              {{- end }}

        - name: johnpaul-app-supporter-app
          image: johnpaul/supporterapp:1.3.0
          ports:
           - conatinersPorts: 3000
           env:
             - name: url 
               {{- if .Values.prodUrlSchema }}
              value: http://{{ .Values.baseUrl }}
              {{- else }}
              value: http://{{ .Values.datacenter }}.non-prod.{{ .Values.baseUrl }}
              {{- end }}
                 
